var annotated_dup =
[
    [ "Base_MIDI_Pitch", "classBase__MIDI__Pitch.html", null ],
    [ "Base_MIDI_Pitch_Collection", "classBase__MIDI__Pitch__Collection.html", "classBase__MIDI__Pitch__Collection" ],
    [ "Base_MIDI_Pitch_Direction", "classBase__MIDI__Pitch__Direction.html", null ],
    [ "Base_MIDI_Pulse", "classBase__MIDI__Pulse.html", null ],
    [ "Base_MIDI_SoftPWM", "classBase__MIDI__SoftPWM.html", null ],
    [ "ByteNoteRegister", "classByteNoteRegister.html", "classByteNoteRegister" ],
    [ "Direct_Collection", "classDirect__Collection.html", "classDirect__Collection" ],
    [ "FirstAvailable_Collection", "classFirstAvailable__Collection.html", "classFirstAvailable__Collection" ],
    [ "IO_74HC595", "classIO__74HC595.html", "classIO__74HC595" ],
    [ "IO_Device", "classIO__Device.html", "classIO__Device" ],
    [ "IO_DigitalWrite", "classIO__DigitalWrite.html", "classIO__DigitalWrite" ],
    [ "IO_Factory", "classIO__Factory.html", "classIO__Factory" ],
    [ "MIDI_Collection_Controller", "classMIDI__Collection__Controller.html", "classMIDI__Collection__Controller" ],
    [ "MIDI_Collection_Factory", "classMIDI__Collection__Factory.html", "classMIDI__Collection__Factory" ],
    [ "MIDI_Device_Controller", "classMIDI__Device__Controller.html", "classMIDI__Device__Controller" ],
    [ "MIDI_Handler", "classMIDI__Handler.html", null ],
    [ "MIDI_Periods", "classMIDI__Periods.html", "classMIDI__Periods" ],
    [ "MIDI_Pulse", "classMIDI__Pulse.html", null ],
    [ "MIDI_Pulse_Controller", "classMIDI__Pulse__Controller.html", "classMIDI__Pulse__Controller" ],
    [ "MIDI_Servo", "classMIDI__Servo.html", null ],
    [ "MIDI_SoftPWM", "classMIDI__SoftPWM.html", null ],
    [ "MIDI_SquareWave", "classMIDI__SquareWave.html", null ],
    [ "MIDI_SquareWave_Direction", "classMIDI__SquareWave__Direction.html", null ],
    [ "MIDI_Toggle", "classMIDI__Toggle.html", null ],
    [ "MIDI_Unipolar", "classMIDI__Unipolar.html", null ],
    [ "NoteDuration", "classNoteDuration.html", "classNoteDuration" ],
    [ "PitchBend", "classPitchBend.html", "classPitchBend" ],
    [ "RoundRobin_Collection", "classRoundRobin__Collection.html", "classRoundRobin__Collection" ],
    [ "SinWave", "classSinWave.html", "classSinWave" ]
];