name=MIDI Device Controller
version=2.0.0
author=MrSolidSnake745
maintainer=Anand Jain <mrsolidsnake745@gmail.com>
sentence=Library for controlling various devices via the MIDI interface
paragraph=Library for controlling various devices via the MIDI interface
category=Device Control
url=https://github.com/solidsnake745/MIDI_Device_Controller
architectures=*
includes=MIDI_Device_Controller.h